---
title: "Princess Component Analysis"
author: "Gus Lipkin, Hailey Skoglund, Jake Greenberg"
output: html_notebook
---

```{r}
library(tidyverse)
library(ggridges)
library(data.table)
library(srt)
library(tidytext)
library(fmsb)
library(arules)
library(arulesViz)
library(factoextra)
library(topicdoc)
library(topicmodels)
```


```{r}
# read in movie data
movieData <- fread("movieData.csv", na.strings = "")[, movie := as.factor(movie)]
movieData[sample(1:nrow(movieData), size = 6)]

# set movie colors
movieColors <- c("Aladdin" = "steelblue1",
                 "Beauty" = "gold1",
                 "Brave" = "darkorange1",
                 "Cinderella" = "skyblue1",
                 "Frog" = "olivedrab2",
                 "Mermaid" = "aquamarine1",
                 "Moana" = "cyan2",
                 "Mulan" = "firebrick3",
                 "Pocahontas" = "burlywood",
                 "Sleeping" = "palevioletred1",
                 "Snow" = "red2",
                 "Tangled" = "mediumorchid1")
```


```{r}
# a function to facilitate reading in the data files
readSRT <- function(x) {
  data.table(read_srt(paste0("MovieSubtitles/Animated/", 
                             x, ".srt"), 
                      collapse = " "))
  }
# read in subtitle files and create a `movie` column for identification
animated <- rbindlist(list(
  readSRT("Aladdin")[, movie := "Aladdin"],
  readSRT("Beauty and the Beast")[, movie := "Beauty"],
  readSRT("Brave")[, movie := "Brave"],
  readSRT("Cinderella")[, movie := "Cinderella"],
  readSRT("The Princess and the Frog")[, movie := "Frog"],
  readSRT("The Little Mermaid")[, movie := "Mermaid"],
  readSRT("Moana")[, movie := "Moana"],
  readSRT("Mulan")[, movie := "Mulan"],
  readSRT("Pocahontas")[, movie := "Pocahontas"],
  readSRT("Sleeping Beauty")[, movie := "Sleeping"],
  readSRT("Snow White and The Seven Dwarfs")[, movie := "Snow"],
  readSRT("Tangled")[, movie := "Tangled"]))
animated[sample(1:nrow(animated), size = 6)]
```


```{r}
# Re-scale the time code so that we can compare rise and fall of the movie
rescale <- function(x){(x-min(x))/(max(x)-min(x))}
# animated[, c("startScale", "endScale") := .(rescale(start), rescale(end)), by = movie]
animated[, ':='(startScale = rescale(start),
                endScale = rescale(end)), by = movie]

# Create a `song` column and set it to False
animated[, song := FALSE]

# Some movies have clearly marked lines that are in song
# animated[movie %in% c("Aladdin", "Beauty", "Sleeping", "Mermaid"), 
#          song := grepl("(<\\/?i>)|(♫)|(\\{\\\\i1?\\})", 
#                        subtitle)][
#            , subtitle := gsub("(<\\/?i>)|(♫)|(\\[Singing\\])|(\\{\\\\i1?\\})", 
#                               "", 
#                               subtitle)]
animated[movie %in% c("Aladdin", "Beauty", "Sleeping", "Mermaid", "Tangled"), 
         ':='(song = grepl("(\\*?<\\/?i>\\*?)|(♫)|(\\{\\\\i1?\\})", 
                           subtitle),
              subtitle = gsub("(\\*?<\\/?i>\\*?)|(♫)|(\\[Singing\\])|(\\{\\\\i1?\\})", 
                              "", 
                              subtitle))]



# Brave lines are not in song
animated[movie %in% c("Brave"), 
         subtitle := gsub("(<i>)|(<\\/i>)|(♫)", 
                          "", 
                          subtitle)]

# These lines are in song
animated[movie == "Cinderella" & 
           n %in% c(54:66, 312:332, 432:452, 479:486, 488, 492:494, 545:546, 
                    548, 550, 552:553, 583:599, 662:667, 723:737, 1034:1038), 
         song := TRUE]
animated[movie == "Frog" & 
           n %in% c(2:5, 110:135, 241:276, 322:399, 713:755, 1095:1112, 1115:1121, 
                    1182:1225, 1233, 1509, 1511, 1599:1605, 1611:1615), 
         song := TRUE]
animated[movie == "Moana" & 
           n %in% c(75:121, 315:329, 504:566, 231:271, 872:892, 900:941, 
                    1136:1159, 1190:1196), 
         song := TRUE]
animated[movie == "Mulan" & 
           n %in% c(52:55,  58:61, 65:85, 89:107, 133:154, 449:492 ,585:618, 
                    760:764), 
         song := TRUE]
animated[movie == "Pocahontas" & 
           n %in% c(1:8, 15:22, 80:92, 160:191, 309:356, 464:497, 766:792, 
                    810:824, 882:941), 
         song := TRUE]
animated[movie == "Snow" & 
           n %in% c(18:57, 412:447, 496:502, 155:166, 167:196, 206:215, 704:720, 
                    727:732), 
         song := TRUE]

# set the movie column to be a factor
animated[, movie := as.factor(movie)]

# Sample some lines to see the changes
animated[sample(1:.N, size = 6)]
```


```{r}
# get sentiments now so we don't have to keep doing it later
afinn <- fread("Lexicons/afinn.csv")
bing <- fread("Lexicons/bing.csv")
nrc <- fread("Lexicons/nrc.csv")

nrcSentiments <- unique(nrc$sentiment)
nrcSentimentsNoPosNeg <- nrcSentiments[-3][-6]
```


```{r}
# generates longer data using each of the three dictionaries
# each word is on its own row
aniAfinnWordLonger <- animated %>%
  unnest_tokens(word, subtitle) %>%
  .[afinn, on = "word", nomatch = 0]
aniAfinnWordLonger[sample(1:nrow(aniAfinnWordLonger), size = 6)]

aniBingWordLonger <- animated %>%
  unnest_tokens(word, subtitle) %>%
  .[bing, on = "word", nomatch = 0]
aniBingWordLonger[sample(1:nrow(aniBingWordLonger), size = 6)]

# in this case, words can be repeated if they have more than one sentiment
aniNrcWordLonger <- animated %>%
  unnest_tokens(word, subtitle) %>%
  .[nrc, on = "word", nomatch = 0]
aniNrcWordLonger[sample(1:nrow(aniNrcWordLonger), size = 6)]

# creates a wider version of aniNrcWordLonger, but aggregates by line
# lines are identified with a `groupID` found by grouping by line number and movie
aniNrcLineWiderNum <- aniNrcWordLonger[, groupID := .GRP, by = list(n, movie)] %>%
  unique() %>%
  .[, !c("word")] %>%
  pivot_wider(names_from = sentiment, values_from = 1, values_fn = length) %>%
  setorderv(c("movie", "start")) %>%
  data.table()
aniNrcLineWiderNum[is.na(aniNrcLineWiderNum)] <- 0
aniNrcLineWiderNum[sample(1:nrow(aniNrcLineWiderNum), size = 6)]

aniNrcLineWiderBool <- aniNrcLineWiderNum %>%
  mutate(across(nrcSentiments, ~ifelse(is.na(.x), FALSE, TRUE)))
aniNrcLineWiderBool[sample(1:nrow(aniNrcLineWiderBool), size = 6)]
```

```{r}
topWords <- aniAfinnWordLonger[!data.table(stop_words), on = "word"] %>%
  .[, .N, by = list(movie, word, song)] %>%
  .[, c("count", "N") := .(N, NULL)] %>%
  .[order(desc(count))] %>%
  .[, indx := seq_len(.N), by = list(movie, song)] %>%
  .[order(movie, desc(count))] %>%
  ungroup()

topWords[indx <= 10L & song == FALSE] %>%
  .[, word := reorder_within(word, count, movie)] %>%
  ggplot() +
  geom_col(aes(x = count, y = word, fill = movie), color = "black") +
  guides(fill = "none") +
  labs(x = NULL, y = NULL) +
  facet_wrap(~movie, scales = "free_y") +
  theme_minimal() +
  scale_fill_manual(values = movieColors[topWords$movie]) +
  scale_y_reordered() +
  labs(title = "Top ten most common spoken words by movie")
ggsave("Graphics/topTenSpoken.png")

topWords[indx <= 10L & song == TRUE] %>%
  .[, Duplicated := duplicated(word)] %>%
  .[, word := reorder_within(word, count, movie)] %>%
  ggplot() +
  geom_col(aes(x = count, y = word, fill = movie, linetype = Duplicated), color = "black") +
  guides(fill = "none") +
  labs(x = NULL, y = NULL) +
  facet_wrap(~movie, scales = "free_y") +
  theme_minimal() +
  scale_fill_manual(values = movieColors[topWords$movie]) +
  scale_y_reordered() +
  theme(legend.position = c(.875, .125),
        axis.title.y = element_blank()) +
  labs(title = "Top ten most common sung words by movie",
       subtitle = "Note: Brave does not have any foreground songs",
       x = "Word occurences per movie")
ggsave("Graphics/topTenSung.png")

# word cloud is still a work in progress
# topWords[indx <= 5L] %>%
#   ggplot() +
#   ggwordcloud::geom_text_wordcloud_area(aes(label = word, size = count, color = movie)) +
#   scale_size_area(max_size = 10) +
#   theme_minimal() +
#   facet_wrap(~song) +
#   scale_color_manual(values = movieColors[topWords$movie])
```


```{r}
tmp <- aniNrcWordLonger[, groupID := .GRP, by = list(n, movie)] %>%
  unique() %>%
  .[, !c("word")] %>%
  pivot_wider(names_from = sentiment, values_from = 1, values_fn = length) %>%
  rowwise(groupID) %>%
  mutate(totalFeeling = sum(c_across(nrcSentiments), na.rm = TRUE)) %>%
  ungroup() %>%
  data.table() %>%
  .[, .(startScale, movie, totalFeeling)] %>%
  .[, .(rep = seq(1, totalFeeling, 1)), by = list(startScale, movie)] %>%
  .[order(movie)] %>%
  .[, movie := factor(movie, levels = rev(movieData$movie))]

tmp %>%
  ggplot() +
  geom_density_ridges(aes(x = startScale, y = movie, fill = movie), 
                      color = "black") +
  scale_fill_manual(values = movieColors[tmp$movie]) +
  theme_ridges() +
  xlim(0, 1) +
  theme(legend.position = "none",
        axis.title.x = element_blank(),
        axis.title.y = element_blank()) +
  labs(title = "NRC emotions over the course of the movie")
ggsave("Graphics/nrcOverMovie.png")
```


```{r}
# by line
# tmp <- aniAfinnWordLonger[, groupID := .GRP, by = list(n, movie)] %>%
#   group_by(movie, song, groupID) %>%
#   summarise(value = sum(value)) %>%
#   arrange(movie, groupID) %>%
#   mutate(movie = factor(movie, levels = movieData$movie),
#          movColors = movieColors[movie],
#          song = ifelse(song, "Sung", "Spoken")) %>%
#   select(movie, song, groupID, value, movColors)

tmp <- aniAfinnWordLonger %>%
  .[, groupID := .GRP, by = list(n, movie)] %>%
  .[, .(value = sum(value)), by = list(movie, song, groupID)] %>%
  .[order(movie, groupID)] %>%
  .[, ':='(movie = factor(movie, levels = movieData$movie),
         song = ifelse(song, "Sung", "Spoken"))]

tmp %>%
  ggplot() +
  geom_violin(aes(x = song, y = value, linetype = song, fill = movie), position = "dodge") + 
  ylim(min(tmp$value), max(tmp$value)) +
  geom_hline(yintercept = 0, size = .5) +
  labs(title = "Variation in positive and negative emotions of lines by type",
       subtitle = "Note: Brave does not have any foreground songs") +
  theme(legend.position = "none",
        axis.title.x = element_blank()) +
  ylab(label = "afinn Lexicon Value") +
  facet_wrap(~movie) +
  scale_fill_manual(values = movieColors[tmp$movie])
ggsave("Graphics/violinPlotLines.png")


# by word
# tmp <- aniAfinnWordLonger %>%
#   arrange(movie) %>%
#   mutate(movie = factor(movie, levels = movieData$movie),
#          movColors = movieColors[movie],
#          song = ifelse(song, "Sung", "Spoken")) %>%
#   select(movie, value, song, movColors, songColors)

tmp <- aniAfinnWordLonger %>%
  .[order(movie)] %>%
  .[, ':='(movie = factor(movie, levels = movieData$movie),
                          song = ifelse(song, "Sung", "Spoken"))] %>%
  .[, .(movie, value, song)]

tmp %>%
  ggplot() +
  geom_violin(aes(x = song, y = value, linetype = song, fill = movie), position = "dodge") + 
  ylim(-5, 5) +
  geom_hline(yintercept = 0, size = .5) +
  labs(title = "Variation in positive and negative emotions of words by type",
       subtitle = "Note: Brave does not have any foreground songs") +
  theme(legend.position = "none",
        axis.title.x = element_blank()) +
  ylab(label = "afinn Lexicon Value") +
  facet_wrap(~movie) +
  scale_fill_manual(values = movieColors[tmp$movie])
ggsave("Graphics/violinPlotWords.png")
```


```{r}
# gets sentiment scores for each movie

# adds up all the individual sentiments for each movie
aniAfinnWordLonger[, 
                   .(totalSentiment = sum(value)), 
                   by = movie][order(desc(totalSentiment))] %>%
  print()

# gets sentiments, counts the number of positive and negative per movie,
#   then gets a total by finding the difference
# unique(aniBingWordLonger[,
#                          n := .N,
#                          by = .(movie, sentiment)][,
#                                                    .(movie, sentiment,
#                                                      n)][order(movie, sentiment)]) %>%
#   pivot_wider(names_from = sentiment, id_cols = c("movie", "n"), values_from = n) %>%
#   data.table() %>%
#   .[, totalSentiment := positive - negative] %>%
#   .[order(desc(totalSentiment))] %>%
#   print()

aniBingWordLonger[, n := .N, by = .(movie, sentiment)] %>%
  .[, .(movie, sentiment, n)] %>%
  dcast(., movie ~ sentiment, value.var = "n") %>%
  .[, totalSentiment := positive - negative] %>%
  .[order(desc(totalSentiment))] %>%
  print()

# counts the number of each sentiment in each movie
# also creates a new column that finds the difference between `negative` and `positive`
#   and adds up the total number of sentiments (not including `negative` and `positive` 
#   to create `totalFeeling`

# aniNrcMovieWider <- aniNrcWordLonger[, .(n = .N), by = .(movie, sentiment)][
#                                                   order(movie, sentiment)] %>%
#   pivot_wider(names_from = sentiment, id_cols = c("movie", "n"), values_from = n) %>%
#   rowwise() %>%
#   mutate(totalSentiment = positive - negative,
#          totalFeeling = sum(c_across(c(2:6, 9:11)))) %>%
#   data.table()

aniNrcMovieWider <- aniNrcWordLonger[, .(n = .N), by = .(movie, sentiment)] %>%
  dcast(., movie ~ sentiment, value.var = "n") %>%
  rowwise() %>%
  mutate(totalSentiment = positive - negative,
         totalFeeling = sum(c_across(c(2:6, 9:11)))) %>%
  data.table()
aniNrcMovieWider
```


```{r, eval=FALSE}
# not particularly useful
transpose(data.table(sentiment = nrcSentimentsNoPosNeg, 
                     max = max(aniNrcMovieWider %>% select(nrcSentimentsNoPosNeg)),
                     min = min(aniNrcMovieWider %>% select(nrcSentimentsNoPosNeg))), 
          make.names = "sentiment") %>%
  rbind(aniNrcMovieWider %>% select(nrcSentimentsNoPosNeg)) %>%
  `rownames<-`(c("max", "min", aniNrcMovieWider$movie)) %>%
  radarchart()
```

```{r}
movieData[aniNrcMovieWider, on = "movie"] %>%
  ggplot() +
  geom_line(aes(x = animatedRelease, y = totalFeeling), color = "darkgrey", size = 1.5) +
  geom_line(aes(x = animatedRelease, y = totalSentiment), color = "darkgrey", size = 1.5) +
  geom_point(aes(x = animatedRelease, y = totalFeeling, color = movie), size = 5) +
  geom_point(aes(x = animatedRelease, y = totalSentiment, color = movie), size = 5) +
  scale_color_manual(values = movieColors[tmp$movie]) +
  theme(legend.position = "none") +
  xlab("Year of Movie Release") +
  ylab("Aggregate Sentiments and Feelings From nrc Lexicon") +
  labs(title = "Checking to see if total feeling changed over time")
ggsave("Graphics/sentimentsByYear.png")
```

```{r, eval=FALSE}
# this didn't create anything useful
nrcFactor <- aniNrcLineWiderBool
nrcFactor <- map_df(nrcFactor %>%
                      # filter(movie == "Mulan") %>%
                      select(nrcSentiments, movie, song), as.factor)
nrcTr <- as(nrcFactor, "transactions")
nrcRules <- apriori(
  nrcTr,
  parameter = list(support = .001, minlen = 4)
  # ,
  # appearance = list(rhs = "song=TRUE")
)
write(nrcRules,
      file = "nrcRules.csv",
      sep = ",",
      quote = TRUE,
      row.names = FALSE)
nrcRules <- fread("nrcRules.csv")
nrcRules <- separate(nrcRules, rules, c("lhs", "rhs"), " => ")
# doing the above bit of IO is way faster than the next line
# nrcRules <- data.table(as(nrcRules %>% inspect(), "data.frame"))

nrcRules[order(lift, decreasing = TRUE), .(lhs, rhs, lift, count)][grepl("movie", rhs)]
```


```{r}
aniNrcLineWiderNum
nrcPCA <- prcomp(aniNrcMovieWider[, .(anger, fear, negative, sadness, 
                                        positive, disgust, surprise, joy, 
                                        anticipation, trust)], scale. = T)

summary(nrcPCA)

fviz_contrib(nrcPCA, choice = "var", axes = 1)
fviz_contrib(nrcPCA, choice = "var", axes = 2)

fviz_pca(
  nrcPCA,
  geom = c("point"),
  repel = TRUE,
  habillage = aniNrcMovieWider$movie,
  palette = movieColors
)

data.table("sentiment" = rownames(nrcPCA$rotation), nrcPCA$rotation) %>%
  melt(id.vars = "sentiment",
       measure.vars = paste0("PC", 1:10),
       variable.name = "PC",
       value.name = "value") %>%
  .[, PC := factor(PC, levels = paste0("PC", 10:1))] %>%
  ggplot() +
  geom_bar(aes(x = sentiment, y = abs(value), fill = PC), position = "fill", stat = "identity", color = "black") +
  scale_fill_manual(values = as.character(data.frame(rev(movieColors[1:10]))[,1])) + 
  theme(axis.text.x = element_text(angle = 60, vjust = .6)) +
  labs(title = "Principal Components as Shares of Occurences of each nrc sentiment",
       fill = "Principal\nComponent") +
  xlab("Sentiment") +
  ylab("Proportion of Principal Component")
ggsave("Graphics/PCA.png")
```

```{r, eval=FALSE}
# Just trust me, you don't want to run this
JJ_wanna_know_average_and_variance_topic_coherence_at_once<- function(your_lda, your_dtm_textdata) {
  temp <- topic_diagnostics(your_lda, your_dtm_textdata) %>%
    select(topic_coherence)
  avg <- temp %>%
    colMeans()
  var <- temp %>%
    var()
  return(avg[1])
}

score_list <- c()

JJ_all_one_function <- function(your_dtm, topic_num){
   for (i in 2:topic_num) {
     score_list <- append(score_list,
                          JJ_wanna_know_average_and_variance_topic_coherence_at_once(LDA(your_dtm, 
                                                                                         k=i, 
                                                                                         control=list(seed=i)), 
                                                                                     your_dtm))
   }
  return(score_list)
}

score_list_output <- JJ_all_one_function(
  animated %>%
    unnest_tokens(word, subtitle, token = "ngrams", n = 2) %>%
    # anti_join(stop_words, by = "word") %>%
    cast_dtm(movie, word, n),
  10
)
score_list_output

plot(
  x = 2:10,
  y = score_list_output,
  type = "l",
  col = "red",
  lwd = 5,
  xlab = "topic number",
  ylab = "avg coherence score",
  main = "distribution of avg coherence scores"
)
# Best coherence at 9 topics
```


```{r}
dtm <- function(x) {
  aniDtm <- animated[movie == x, movie := as.character(x)] %>%
    unnest_tokens(word, subtitle) %>%
    # anti_join(stop_words, by = "word") %>%
    cast_dtm(movie, word, n) %>%
    LDA(k = 9) %>%
    terms(5)
  return(aniDtm)
}

aniTopics <- lapply(as.character(unique(animated$movie)), FUN = dtm)
topics <- data.table("movie" = rep(as.character(unique(animated$movie)),
                                   each = 5),
                     do.call(rbind.data.frame, aniTopics)) %>%
  melt(id.vars = "movie",
       measure.vars = paste0("Topic ", 1:9),
       variable.name = "topic",
       value.name = "ngram") %>%
  unnest_tokens(word, ngram) %>%
  anti_join(stop_words, by = "word") %>%
  unique() %>%
  arrange(movie, topic) %>%
  right_join(aniAfinnWordLonger[, .(movie, word)]) %>%
  .[, .N, by = c("movie", "topic", "word")]

wordcloud <- wordcloud2::wordcloud2(data = topics[, .(word, N)],
                       color = gplots::col2hex(as.character(movieColors[topics$movie]))
                       )
wordcloud
htmlwidgets::saveWidget(wordcloud, "Graphics/wordcloud.html", selfcontained = FALSE)
webshot::webshot("Graphics/wordcloud.html", "Graphics/wordcloud.png", delay = 10)
```

```{r}
dtmBigram <- function(x) {
  aniDtm <- animated[movie == x, movie := as.character(x)] %>%
    unnest_tokens(word, subtitle, token = "ngrams", n = 3) %>%
    # anti_join(stop_words, by = "word") %>%
    cast_dtm(movie, word, n) %>%
    LDA(k = 9) %>%
    terms(5)
  return(aniDtm)
}

aniTopics <- lapply(as.character(unique(animated$movie)), FUN = dtmBigram)
topics <- data.table("movie" = rep(as.character(unique(animated$movie)),
                                   each = 5),
                     do.call(rbind.data.frame, aniTopics)) %>%
  melt(id.vars = "movie",
       measure.vars = paste0("Topic ", 1:9),
       variable.name = "topic",
       value.name = "ngram") %>%
  # unnest_tokens(word, ngram) %>%
  # anti_join(stop_words, by = "word") %>%
  select(-topic) %>%
  unique() %>%
  # right_join(aniAfinnWordLonger[, .(movie, word)]) %>%
  .[, .N, by = c("movie", "ngram")] %>%
  arrange(desc(N))

greplNgram <- function(x) {
  ifelse(grepl(x, animated$subtitle),
    return(data.table("movie" = animated$movie[grepl(x, animated$subtitle)], 
                      "subtitle" = animated$subtitle[grepl(x, animated$subtitle)],
                      "ngram" = x)),
    return(data.table("movie" = NA, 
                      "subtitle" = NA,
                      "ngram" = NA)))
}
test <- lapply(topics$ngram, greplNgram)
test <- rbindlist(test)
test <- test[!is.na(movie)]
test <- test %>%
  group_by(ngram) %>%
  count(ngram) %>%
  data.table() %>%
  arrange(desc(n))

wordcloud <- wordcloud2::wordcloud2(data = test[, .(ngram, n)])
wordcloud
htmlwidgets::saveWidget(wordcloud, "Graphics/wordcloudTrigram.html", selfcontained = FALSE)
webshot::webshot("Graphics/wordcloudTrigram.html", "Graphics/wordcloudTrigram.png", delay = 10)
```










